apiVersion: v1
kind: Service
metadata:
  name: {{ include "mediaWiki.fullname" . }}
  labels:
    {{- include "mediaWiki.labels" . | nindent 4 }}
  {{- if eq .Values.service.useExternalLB false }}
  annotations:
    {{- if eq .Values.csp "google" }}
    cloud.google.com/load-balancer-type: "Internal"
    {{- else if eq .Values.csp "aws" }}
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    {{- else if eq .Values.csp "azure" }}
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    {{- end }}
  {{- end }}
spec:
  type: {{ default "LoadBalancer" .Values.service.type }}
  {{- if and (eq .Values.service.useExternalLB false) (eq .Values.service.type "LoadBalancer") }}
  loadBalancerSourceRanges:
  {{- range .Values.service.internalLB.loadBalancerSourceRanges }}
    - {{ . | quote }}
  {{- end }}
  {{- end }}
  ports:
    - port: {{ default 80 .Values.service.ui.ports.external.http }}
      targetPort: {{ default 80 .Values.service.ui.ports.internal.http  }}
      protocol: TCP
      name: http
  selector:
    {{- include "mediaWiki.selectorLabels" . | nindent 4 }}
